Integration tests
software-mansion-labs/elixir-janus pull request #11
Opened 2020-09-03 12:49 UTC by Qizot

2020-09-03 14:06 UTC, bblaszkow06 requested changes

2020-09-03 14:06 UTC, bblaszkow06 commented on janus_integration/docker-compose.yml
> +    image: swmasnion/janus
```suggestion
    image: swmansion/janus
```

2020-09-03 14:06 UTC, bblaszkow06 commented on janus_integration/config/test.exs
> +  gateway_ws_admin_url: System.get_env("GATEWAY_WS_ADMIN_URL") || "ws://localhost:7188"
You can put it in config and remove `dev` and `test` configs, I don't think it's ever going to be needed

2020-09-03 14:06 UTC, bblaszkow06 commented on janus_integration/janus-config/janus.jcfg
> +general: {
Have you changed anything in these configs? `docker-janus` already has such configs. In you-know-which project we added these separately because we wanted to override the ones in docker-janus

2020-09-03 14:06 UTC, bblaszkow06 commented on janus_integration/mix.exs
> +      {:elixir_janus_plugin_videoroom,
Is this really needed? I don't see any call using it. You should either test it as well or remove from deps (maybe the second option would be better if done together with adding similar test to `elixir_janus_plugin_videoroom`)

2020-09-03 14:22 UTC, Qizot commented on janus_integration/mix.exs
> +      {:elixir_janus_plugin_videoroom,
Yup, forgot to remove that

2020-09-04 11:20 UTC, bblaszkow06 approved these changes

2020-09-04 11:43 UTC, merged