Added basic async request handling.
software-mansion-labs/elixir-janus pull request #13
Opened 2020-09-15 14:16 UTC by Hajto

2020-09-15 14:17 UTC, Hajto commented
I went with storing type of request instead of response counter.

2020-09-15 14:32 UTC, bblaszkow06 commented on lib/connection/transaction.ex
> +  defp should_delete?({:ok, %{"janus" => "ack"}}, :async_request), do: true
I think we should not delete the transaction on ack of async request

2020-09-15 14:32 UTC, bblaszkow06 commented on lib/connection/transaction.ex
> +  defp should_delete?({:ok, %{"janus" => "ack"}}, :async_request), do: true
Make sure the tests cover that case

2020-09-15 14:32 UTC, bblaszkow06 commented on lib/connection.ex
> +    GenServer.call(server, {:call, payload, timeout, :async_request}, timeout)
Remember to expose this in Session

2020-09-21 16:17 UTC, bblaszkow06 commented on lib/connection/transaction.ex
> +          :ets.delete(pending_calls_table, transaction)
Actual deletion should be logged

2020-09-22 15:17 UTC, bblaszkow06 requested changes

2020-09-22 15:17 UTC, bblaszkow06 commented on test/connection/transaction_test.exs
> +      # Ensure transaction is deleted
Is it deleted?

2020-09-22 15:17 UTC, bblaszkow06 commented on test/session_test.exs
> +    test "ignore ack", %{connection: conn} do
We're missing test cases for two responses arriving - [ack, event] and [event, ack]

2020-09-22 15:17 UTC, bblaszkow06 commented on lib/connection/transaction.ex
> +          :ets.delete(pending_calls_table, transaction)
We can change the way logs work here - please log from every case, this way without additional log lines we can include info about what happened (e.g. something was or wasn't removed from ets table)

2020-09-22 15:17 UTC, bblaszkow06 commented on lib/connection.ex
> +           "sender" => sender
As mentioned in person, this fields will only be included in some requests, so we cannot match on them here

2020-09-23 11:01 UTC, bblaszkow06 commented on lib/connection.ex
> +           "sender" => sender
I've decided to stick to the Janus original payload shape and only filter out transaction. Modifying the returned payload has to be done in a bigger refactor allowing to document such shape. See #17

2020-09-23 11:30 UTC, bblaszkow06 commented on test/session_test.exs
> +    test "ignore ack", %{connection: conn} do
Left this as TODO since it's tested in lower layers

2020-09-23 11:37 UTC, merged